### ISSUE TITLE
Auditors not saving/sending data

### ISSUE THREAD

**Issue by budang** [CuriousG102/turkey#34]
Sample exported XML:

`...`
`<auditors>`
`<user_agent/>`
`<keypresses_total/>`
`<clicks_total/>`
`<keypresses_specific/>`
`</auditors>`
`...`

**Comment by CuriousG102** [comment]
Need more data. Is this from an embed or on a page?

**Comment by budang** [comment]
on a page

**Comment by CuriousG102** [comment]
Look at projects. Please verify it is not the issue already noted.

Miles Hutson
(214) 929-5684

**Comment by budang** [comment]
I see it, thanks for the clarification
