### ISSUE TITLE
Intent of answers_handler.js is unclear

### ISSUE THREAD

**Issue by CuriousG102** [CuriousG102/turkey#9]
https://github.com/CuriousG102/turkey/blob/c90121c9749f7796ca499fc3378e1d1b5fd631e0/web/turkey/survey/static/survey/js/steps/answers_handler.js

@budang I am attempting to make a template, and would like to preserve some of your work as possible. But I can't tell what the intent of answers_handler.js is. There is no attached template code, the code appears not to be generalized or work for multiple instances of a step, and the code doesn't match javascript's grammar (line 27 `'name'  :   'multiple_choice_text';`, lines 13, 18, and 23 commas are present).

If it's ok with you I plan to just proceed with a new file.

**Comment by CuriousG102** [comment]
So much stuff is changing because I didn't think about multiple instances of steps. No point in talking about this file anymore. Closing

**Comment by budang** [comment]
Sorry for the late response, but you're right this file is not needed
